server:
  port: 8000
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1

spring:
  application:
    name: gateway
  profiles:
    active: dev

blackIP:
  continueCounts: ${counts:3}    # ip连续请求的次数
  timeInterval: ${interval:20}    # ip判断的时间间隔，单位：秒
  limitTimes: ${times:30}         # 限制的时间，单位：秒